### ISSUE TITLE
Searching and sorting algorithms in Java

### ISSUE THREAD

**Issue by aastha01chauhan** [opencodeiiita/Code-Trouble#1]
**Description**

I want to contribute majorly used searching and sorting algorithms used in Competitive programming as a beginner
**Important Checklist**
 I have read the contribution guidelines before making this issue.
 I have verified this issue program is not already implemented
**Languages and Assignees:**
 Python: 
 Java: 
 C: 
 C++: 
**Notes**
Anything you would like to discuss.

**Comment by rag-hav** [comment]
Hi @aastha01chauhan, thanks for your interest!

Unfortunately there appears to be some misunderstanding. Code-Trouble will have issues created by us (the mentors), in each issue you will have to solve a task related to competitive coding. These issues and tasks will be created on 4 October, when the contribution period starts.

There will be no documentation creation.

Hope this helps, see you when contribution period starts!

**Comment by vipulranjansahu** [comment]
claim
