### ISSUE TITLE
Binary Exponentiation in Java and/or python

### ISSUE THREAD

**Issue by aastha01chauhan** [opencodeiiita/Code-Trouble#2]
Binary exponentiation is a technique which allows to calculate a^n using only O(logn) multiplications (instead of O(n) multiplications required by the naive approach.

**Comment by aastha01chauhan** [comment]
Please assign this issue to me.

**Comment by karankc23** [comment]
Claim, I want to work on this issue,

**Comment by Anushh23** [comment]
claim

**Comment by shadaanhussain** [comment]
I want this issue. Please assign it to me.

**Comment by sachin-raghuwanshi** [comment]
assign/

**Comment by isharawat** [comment]
I can solve this issue. please assign it to me

**Comment by anshumanjain2010** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by The-Divyansh** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by Pranav-22-aditya** [comment]
claim

**Comment by divakar932** [comment]
claim

**Comment by saloni33** [comment]
claim

**Comment by rag-hav** [comment]
Hello everyone! 

Issues will be created by us (mentors). The first issue will be up sometime tommorow.

Thanks
