### ISSUE TITLE
Task 2: Love Trouble

### ISSUE THREAD

**Issue by anshg0711** [opencodeiiita/Code-Trouble#5]
### Resolve Jalwa's Love Troubles!
Complete task 1 by debugging _debug_code.cpp_
You have **1 day** until Babita ji finds someone else to do this.
Note: Don't completely overwrite the code, only edit it.

**Comment by vemulapandu** [comment]
claim

**Comment by ashutosh3027** [comment]
claim

**Comment by Perry0107** [comment]
claim

**Comment by underoot-iota** [comment]
claim

**Comment by Ksathwik03** [comment]
claim

**Comment by divakar932** [comment]
claim

**Comment by hardikarora2** [comment]
claim

**Comment by devmrfitz** [comment]
clain

**Comment by anirudhhhh** [comment]
claim

**Comment by gaurav1058** [comment]
claim

**Comment by Anushh23** [comment]
claim

**Comment by Code-Aditya-14** [comment]
claim

**Comment by aviralgupta752** [comment]
claim

**Comment by daniel-aracquine** [comment]
claim

**Comment by Pranav-22-aditya** [comment]
claim

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by anshumanjain2010** [comment]
claim🙄

**Comment by souvenger** [comment]
claimmmmmmm

**Comment by saloni33** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by codelord09** [comment]
claim

**Comment by Mantraraj8472** [comment]
Claim

**Comment by shashwat-mittal** [comment]
Since 24hrs have been completed till the issue was assigned, i would please like to work on this issue

**Comment by jalanprakhar** [comment]
claim 24 hours completed!

**Comment by Ksathwik03** [comment]
Its 4 i want to claim the issue since the time has been completed.

**Comment by jalanprakhar** [comment]
claimmmmmmmmmmmmmmmmmmmmmmm!

**Comment by daniel-aracquine** [comment]
it's 4:03 pm . 1 day is over .. I want to claim this

**Comment by shashwat-mittal** [comment]
time was up when i had commented, please assign the issue to me..

**Comment by anshg0711** [comment]
@vemulapandu was not able to help Babita!!

**Comment by Puja-Saraf** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by shashwat-mittal** [comment]
claim

**Comment by anshg0711** [comment]
Issue Closed, a new issue will be made!
