### ISSUE TITLE
Task 1.2: Fill in 5 blanks

### ISSUE THREAD

**Issue by rag-hav** [opencodeiiita/Code-Trouble#7]
This is an open for all task, you do not need to claim it.

Fill in any 5 blank lines in the *secret_file.txt* according to the pattern (refer to #3 ) . If any previous PR has filled the blanks before yours, then it will be rejected and you will have to make a new PR.

Do not disclose the pattern to anyone.

Edit-
You have to fill in the blank lines, dont add new lines! Total line count should be 2000

**Comment by jalanprakhar** [comment]
claim

**Comment by isharawat** [comment]
Claim

**Comment by Mansivjain00** [comment]
claim

**Comment by bipulkmr-crypto** [comment]
> claim

It is open for all.

**Comment by nitheesh96** [comment]
claim

**Comment by rushilpatra** [comment]
claim

**Comment by nitheesh96** [comment]
claim

**Comment by rag-hav** [comment]
@rushilpatra  @nitheesh96 

> This is an open for all task, you do not need to claim it.
