### ISSUE TITLE
Task 2: Love-Trouble (Open for all, first PR)

### ISSUE THREAD

**Issue by rag-hav** [opencodeiiita/Code-Trouble#94]
### Resolve Jalwa's Love Troubles!
Complete task 2 by debugging debug_code.cpp
Help Babita Ji as fast as possible.

#### This is an open issue. No need to claim this

The first correct pr will get the points!

Note: Only edit the code, do not rewrite it.

**Comment by shashwat-mittal** [comment]
claim

**Comment by Tanushree-coder** [comment]
claim

**Comment by shashwat-mittal** [comment]
please assign the issue to me

**Comment by Perry0107** [comment]
claim

**Comment by anshg0711** [comment]
No more pr

**Comment by anshg0711** [comment]
no more pr

**Comment by codelord09** [comment]
Why this issue closed?

**Comment by codelord09** [comment]
@rag-hav @ansh0711
